<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Welcome Mail</title>
<style type="text/css">
body,td,th {
	font-family: Verdana, Geneva, sans-serif;
}
</style>
</head>

<body>
<p align="center"><img src="http://swiftcloud.me/simplesaml/resources/swiftLogo.png" alt="Swift Logo" width="222" height="29"/></p>
<table width="96%" border="0" align="center" cellpadding="20" cellspacing="4" bgcolor="#990000">
  <tr>
    <td valign="top" bgcolor="#FFFFFF">Hi <?php echo $receiver; ?>,
      <p>Welcome to Swift!<br />
    </p>
      <p>	We're delighted to meet you, and really look forward to helping you grow your business.
      Your Email address added in swift contact list.</p>
      <p>Added By : <b><?php echo $addedByMail; ?></b></p>
      
      <h3 align="center"><a href="#" target="_new">Click Here to Create Password</a></h3><br />
      <p>&nbsp;</p>
      <p><strong>Say, you like low prices, right?</strong></p>
      <p>If you'll help us spread the word, we'd appreciate it! To say thanks for helping us grow, we'll add an extra 30 points to your account. You can customize your message.</p>
      <table width="90%" border="0" align="center" cellpadding="15" cellspacing="2" bgcolor="#999999">
        <tr>
        	<td><b>Click to Social service for taking a test drive on Swift Cloud... so far, so good.</b></td>
        </tr>
        <tr>
          <td align="center" bgcolor="#FFFFFF"><p><a href="http://www.facebook.com/sharer/sharer.php?s=100&amp;p[url]=http://swiftcloud.me/&amp;p[title]=Taking%20a%20free%20test%20drive%20of%20TheSwiftCloud.com&amp;p[summary]=I'm%20taking%20a%20test%20drive%20of%20Swift%20Cloud%20-%20so%20far,%20so%20good%20-%20try%20it%20free%20at%20http://swiftcloud.me" target="_new"><img src="http://swiftcloud.me/images/color-facebook-128.png" alt="Facebook" width="100" height="100" border="0" /></a>
        	<a href="http://twitter.com/home?status=I'm%20taking%20a%20test%20drive%20of%20Swift%20Cloud%20-%20so%20far,%20so%20good%20-%20try%20it%20free%20at%20http://swiftcloud.me" target="_new"><img src="http://swiftcloud.me/images/color-twitter-128.png" alt="Twitter" width="100" height="100" border="0" /></a>
          	<a href="https://plus.google.com/share?url=http://swiftCloud.me" target="_new"><img src="http://swiftcloud.me/images/Google-plus-icon.png" alt="Google+" width="100" height="100" border="0" /></a>
          </td>
        </tr>
      </table>
      <p>Thanks for helping us grow and keep our advertising costs low. The faster we grow, the more we can add more features to help <em>you </em>grow your business.<br />
  </p>
<p>&nbsp;</p>
<p>Did you know your Swift login is a passport to a whole cloud based system? Your login above also works with...</p>
<table width="100%" border="0" cellspacing="0" cellpadding="20">
  <tr>
    <td width="1%"><img src="http://swiftradar.com/images/swiftradar.com.png" alt="Swift Radar" width="318" height="48" /></td>
    <td width="99%" valign="top">Your 360° View of what matters to you. Includes social media monitoring, Press &amp; PR opportunities tools, Search Engine Results (&quot;SERP&quot;) tracking and more. See the <a href="#">Demo Video here</a>.</td>
  </tr>
  <tr>
    <td><img src="http://swiftmarketing.com/images/swift-marketing.png" alt="Swift Marketing" width="391" height="48" /></td>
    <td valign="top">Marketing tools &amp; training, including marketing automation such as mass email &amp; SMS, pre-scheduled social media, autoresponders, lead scoring and more. See the <a href="#">Demo Video here</a>.</td>
  </tr>
  <tr>
    <td><img src="http://swiftform.com/images/Swift-website-form.png" alt="SwiftForm" width="296" height="48" /></td>
    <td valign="top">&nbsp;</td>
  </tr>
</table>
<p>&nbsp;</p>
<p>With several more applications already in development.</p></td>
  </tr>
</table>
<p>&nbsp;</p>
</body>
</html>