<body style='font-family:Verdana, Geneva, sans-serif;fontsize:20px;font-style:italic; background:#dddddd; margin:0; padding:0;'>
	<div style="width:870px; margin:0 auto;">
    	<table>
      		<tbody>
        		<tr>
          			<td width='150px' style="background:#dddddd;"></td>
          			<td style="background:#fff;border:1px solid #086fd6; border-radius:7px;padding:0;">
            			<div style='float:left; width:568px; float:left;'>
        					<div style=" border-bottom:3px solid #086fd6; width:100%; float:left;">
                				<div style="color:#F00;font-style:italic;font-size:25px;">
                 					<table width="100%">
                 						<tbody>
                 							<tr>
                        						<td width="100%"  style="padding:0 160px 0 160px;">
                            						<img style="float:left;padding-left:10px;margin:10px 0;"src="http://swiftcloud.me/images/Mail_flag.png"/>
                             						<h1 style="color:#F00;display: inline-block;line-height: 80px;margin:0;">Swift</h1>
                            					</td>
                        					</tr>
                     					</tbody>
                 					</table>
                				</div><!--logo-->
              				</div><!--headerEm-->
              
              				<div style='padding:30px; float:left; width:89%;font-family:Verdana, Geneva, sans-serif;'>
                				<div style='float:left;  margin-bottom:30px; width:100%;'>
                 
									<div style='font-size:14px; width:95%; padding-left:30px;'>
                    				<!------- Content div ---------------------------------------->
                        
                    					<center><h2 style='color:#F00; font-weight:normal; margin:3px 0;'>Lost Password</h2></center> 
                        
                        				<p style='margin:0; padding:20px 0px 0px 0px;color:#666666;'>To reset your password:</p> 
                        				<br />
                                        
                                        <div style='margin:auto; width:200px;'>
                 							<a href="%RESETPASSLINK%" id="submit" target="_new" title="Reset Password" style='float:left;width:150px;font-size:15px; font-weight:bold; padding:5px 20px; background:#33a9e5; border:1px solid #2288cc; color:#fff; -webkit-border-radius: 20px; -moz-border-radius: 20px; border-radius: 20px;  cursor:pointer; text-align: center;text-decoration: none;'>Reset Password</a>
                  						</div>
                                        
                                        <br />
                                        <br />
                                        <p style='margin:0; padding:20px 0px 0px 0px;color:#666666;'>This token is valid for only 5 days. If this token expire, you have to request a new token. <a href="http://swiftcloud.me/simplesaml/module.php/selfregister/lostPassword.php?URL=swiftcloud.me" target="_new" title="Create New Token">Click Here to create new token</a></p>
                         				<br /><br />
                                        <div style='margin:3px 0; padding-bottom:10px;line-height:3px;color: #666666;'>
                                          <p>Sincerely, </p>
                                          <p>Roger Vaughn</p>
                                          <p>CEO, SwiftCloud, Inc.</p>
                                          <p>roger@SwiftCloud.me</p>
                                        </div>
                        			<!------ End ------------------------------------------------>
                                    </div><!--colunm-->
                				</div><!--row-->
                			</div>
              			</div><!--contentEm-->
               		</td>
          			<td width='150px' style='background:#dddddd; border-left:1px solid #ccc;'></td>
        		</tr>
      		</tbody>
    	</table>
  	</div><!--wraper-->
</body>