<body style='font-family:Verdana, Geneva, sans-serif;fontsize:20px;font-style:italic; background:#dddddd; margin:0; padding:0;'>
<div style="width:870px; margin:0 auto;">
    <table>
      <tbody>
        <tr>
          <td width='150px' style="background:#dddddd;">
          </td>
          <td style="background:#fff;border:1px solid #086fd6; border-radius:7px;padding:0;">
            <div style='float:left; width:568px; float:left;'>
        
              <div style=" border-bottom:3px solid #086fd6; width:100%; float:left;">
                <div style="color:#F00;font-style:italic;font-size:25px;">
                 <table width="100%">
                 	<tbody>
                 		<tr>
                        	<td width="100%"  style="padding:0 160px 0 160px;">
                            <img style="float:left;padding-left:10px;margin:10px 0;"src="http://swiftcloud.me/images/Mail_flag.png"/>
                             <h1 style="color:#F00;display: inline-block;line-height: 80px;margin:0;">Swift</h1>
                            </td>
                        </tr>
                     </tbody>
                 </table>
            
                </div><!--logo-->
              </div><!--headerEm-->
              
              <div style='padding:30px; float:left; width:89%;font-family:Verdana, Geneva, sans-serif;'>
                <div style='float:left;  margin-bottom:30px; width:100%;'>
                 
					<div style='font-size:14px; width:95%; padding-left:30px;'>
                    <!------- Content div ---------------------------------------->
                        
                    <center ><h2 style='color:#F00; font-weight:normal; margin:3px 0;'>Welcome to SwiftCloud!</h2></center> 
                        
                        <p style='margin:0; padding:20px 0px 0px 0px;color:#666666;'>Hi there %FIRSTNAME%!</p> 
                        <div style='padding:10px 0 5px;'>
                            <!--<p style='color:#666; font-size:14px; margin:3px 0;'>Welcome to SwiftCloud. We think you rock.</p> -->
<br>                        <p style='color:#666; font-size:14px; margin:3px 0;'>I'm RogerV, CEO and founder of SwiftCloud. I just wanted to welcome you, %FIRSTNAME%, to SwiftCloud, and ask you a question: how can we help you make life better? Earn more money? Save more time?
 </p> 
 <br>                       <p style='color:#666; font-size:14px; margin:3px 0; padding:10px 0 5px;'> We'd love to hear from you %FIRSTNAME% - you can just reply to this message. </p>
                        </div>
                        <p style='color:#666; font-size:14px; margin:3px 0;padding:10px 0 5px;'>We're pushing as hard as we can to build amazing code quickly, and appreciate your understanding for any "edge instability" as we grow. As the race car Mario Andretti once said, "If everything seems under control, you're not going fast enough". The core of each application will remain stable, so if anything does pop up after slipping through our QC team, it will probably be on only the "bleeding edge" newest features. 
</p>
						<p style='color:#666; font-size:14px; margin:3px 0;padding:10px 0 5px;'>That said, we'd love for you to test them as you see new things in the toolsuite.
</p>
						<p style='color:#666; font-size:14px; margin:3px 0;padding:10px 0 5px;'>As CEO, I'd like to ask you a small favor - just let us know your thoughts. If you wish it did a certain thing, spot something broken, think we should add something in, I personally would love to hear it. We aim to be the best at what we do, and don't care (yet!) about being the biggest... just the best. For you.
</p>
						<p style='color:#666; font-size:14px; margin:3px 0;'>Welcome, and we're glad you're here.
</p>
                        <br>
                        
                        <div style='margin:3px 0; padding-bottom:2px;color:#666;line-height:5px;'>
                           <p>Login Now</p>
                           <p>Tell a Friend</p>
                           <p>Learn how to get the most out of SwiftCloud </p>
                         </div>
                        
                         <div style='margin:3px 0; padding-bottom:10px;line-height:3px;color: #666666;'>
                          <p>Sincerely, </p>
                          <p>Roger Vaughn</p>
                          <p>CEO, SwiftCloud, Inc.</p>
                          <p>roger@SwiftCloud.me</p>
                        </div>
                        
                    <!------ End ------------------------------------------------>
                    
                  </div><!--colunm-->
                </div><!--row-->
                
                
                
                <div style='margin:auto; width:200px;'>
                 <a href="http://swiftcloud.me/user/login" id="submit" target="_new" title="Swift Login" style='float:left;width:150px;font-size:15px; font-weight:bold; padding:5px 20px; background:#33a9e5; border:1px solid #2288cc; color:#fff; -webkit-border-radius: 20px; -moz-border-radius: 20px; border-radius: 20px;  cursor:pointer; text-align: center;text-decoration: none;'>Login</a>
                   
                  </div>
                </div>
              </div><!--contentEm-->
               
              
              
           
          </td>
          <td width='150px' style='background:#dddddd; border-left:1px solid #ccc;'>

          </td>
        </tr>
      </tbody>
    </table>
  </div><!--wraper-->
</body>