<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/userList.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Agent Users</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Agent users list
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="agentUserTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 5%;">Id</th>
                                    <th>Name</th>
                                    <th>Phone No</th>
                                    <th>Available Bal.</th>
                                    <th style="width: 9%;">Status</th>
                                    <th style="width: 20%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($agentUser) > 0) {
                                    foreach ($agentUser as $user) {
                                        ?>
                                        <tr>
                                            <td><?=$user['Id']?></td>
                                            <td><?=$user['name']?></td>
                                            <td><?=$user['phoneNo']?></td>
                                            <td><?=$user['avaiTransBal']?></td>
                                            <td class="text-center">
                                                <?php if ($user['accountStatus'] == 'Active') { 
                                                    ?>
                                                        <button class="btn btn-success btn-circle" type="button" title="Active">
                                                            <i class="fa fa-check"></i>
                                                        </button>
                                                    <?php
                                                } else {?>
                                                        <button class="btn btn-danger btn-circle" type="button" title="Deactive">
                                                            <i class="fa fa-pause"></i>
                                                        </button>
                                                <?php } ?>
                                            </td>
                                            <td class="tool-tip">
                                                <button data-placement="top" data-toggle="tooltip" data-original-title="Change Credit" class="btn btn-primary btn-circle" type="button">
                                                    <i class="fa fa-money" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-warning btn-circle" type="button" data-placement="top" data-toggle="tooltip" data-original-title="Change Password">
                                                    <i class="fa fa-ge" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-primary btn-circle" type="button" data-placement="top" data-toggle="tooltip" data-original-title="Show Reports">
                                                    <i class="fa fa-database" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-danger btn-circle" type="button" data-placement="top" data-toggle="tooltip" data-original-title="Delete User">
                                                    <i class="fa fa-trash" style="font-size: 1.4em;"></i>
                                                </button>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
   
</div>
<!-- /#page-wrapper -->