<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/userList.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header pull-left">Agent Users</h1>
            <button style="margin-top: 37px;" data-target="#newAgentUser" data-toggle="modal" class="btn btn-primary btn-lg pull-right">
                Create New Agent User
            </button>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Agent users list
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="agentUserTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 5%;">Id</th>
                                    <th>Name</th>
                                    <th>Phone No</th>
                                    <th>Available Bal.</th>
                                    <th style="width: 9%;">Status</th>
                                    <th style="width: 15%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($agentUser) > 0) {
                                    foreach ($agentUser as $user) {
                                        ?>
                                        <tr>
                                            <td><?=$user['Id']?></td>
                                            <td><?=$user['name']?></td>
                                            <td><?=$user['phoneNo']?></td>
                                            <td><?=$user['avaiTransBal']?></td>
                                            <td class="text-center">
                                                <?php if ($user['accountStatus'] == 'Active') { 
                                                    ?>
                                                        <button class="btn btn-success btn-circle confirm" link="<?php echo $this->basePath() ?>/admin/changeStatus/<?=$user['Id']?>/0" type="button" title="Active">
                                                            <i class="fa fa-check"></i>
                                                        </button>
                                                    <?php
                                                } else {?>
                                                        <button class="btn btn-danger btn-circle confirm" link="<?php echo $this->basePath() ?>/admin/changeStatus/<?=$user['Id']?>/1" type="button" title="Deactive">
                                                            <i class="fa fa-pause"></i>
                                                        </button>
                                                <?php } ?>
                                            </td>
                                            <td class="tool-tip">
                                                <button data-placement="top" data-toggle="modal" onclick="changeCredit(<?=$user['Id']?>);" data-target="#chageUserCredit" title="Change Credit" class="btn btn-primary btn-circle" type="button">
                                                    <i class="fa fa-money" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-warning btn-circle" onclick="changePassword(<?=$user['Id']?>);" data-target="#changeUserPassword" data-toggle="modal" type="button" data-placement="top" title="Change Password">
                                                    <i class="fa fa-key" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-primary btn-circle" data-content="<a href='<?php echo $this->basePath() ?>/admin/transferReport/<?=$user['Id']?>'>Transfer Report</a><br/><a href='<?php echo $this->basePath() ?>/admin/agentDaywiseReport/<?=$user['Id']?>'>Daywise Report</a>" data-placement="bottom" data-toggle="popover" data-container="body" type="button" title="Show Reports">
                                                    <i class="fa fa-database" style="font-size: 1.4em;"></i>
                                                </button>
                                                <!--<button class="btn btn-danger btn-circle" type="button" data-placement="top" data-toggle="tooltip" data-original-title="Delete User">
                                                    <i class="fa fa-trash" style="font-size: 1.4em;"></i>
                                                </button>-->
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
   
</div>
<!-- /#page-wrapper -->

<!-- Modal -->
    <div class="modal fade" id="newAgentUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Create New Agent User</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/createUser">
                        <input value="agent" type="hidden" name="userRoll">
                        <input name="userId" id="userId" value="0" type="hidden">
                        <div class="form-group">
                            <label>Name</label>
                            <input placeholder="Enter Name" name="name" class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <label>Phone No</label>
                            <input placeholder="Enter Phone No" name="phoneNo" class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <label>Password</label>
                            <input placeholder="Enter Password" name="password" class="form-control">
                        </div>
                        
                        <button class="btn btn-default" type="submit">Create User</button>
                        <button class="btn btn-default" type="reset">Reset Button</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    
     <div class="modal fade" id="changeUserPassword" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Change Password</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/changeUserPassword">
                        <input value="agent" type="hidden" name="userRoll">
                        <input name="userId" id="userId" value="0" type="hidden">
                        <div class="form-group">
                            <label>New Password</label>
                            <input placeholder="Enter New Password" name="password" class="form-control">
                        </div>
                        
                        <button class="btn btn-default" type="submit">Update Password</button>
                        <button class="btn btn-default" type="reset">Reset Button</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
     </div>
    
     <div class="modal fade" id="chageUserCredit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Change User Credit</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/changeUserCredit">
                        <input value="agent" type="hidden" name="userRoll">
                        <input name="userId" id="userId" value="0" type="hidden">
                        <div class="form-group">
                            <label>Select Balance Action Type</label>
                            <select class="form-control" name="type">
                                <option value="credit">Credit</option>
                                <option value="debit">Debit</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label>Balance</label>
                            <input placeholder="Enter Balance" name="balVal" class="form-control">
                        </div>
                        
                        <button class="btn btn-default" type="submit">Save</button>
                        <button class="btn btn-default" type="reset">Reset Button</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
     </div>