<?php
echo $this->headLink()
        ->appendStylesheet($this->basePath() . '/css/example.css')
        ->appendStylesheet($this->basePath() . '/css/jquery.countdown.timer.css');

echo $this->headScript()
        ->appendFile($this->basePath() . '/js/jquery.timeout.interval.idle.js')
        ->appendFile($this->basePath() . '/js/jquery.countdown.counter.js')        
        ->appendFile($this->basePath() . '/js/myjs/dashboard.js');

?>
<script>
    $(document).ready(function() {
        CounterInit(<?php echo $remainigTime; ?>);
    });
</script>
<div id="page-wrapper">
    <div class="row">
        <div style="width:40%;margin-top:10px;" class="pull-left">
            <b>Selected Mode : <?php if($drawMode['drawMode'] == 1) {
                echo 'Minimum Mode';
            } else if($drawMode['drawMode'] == 2) {
                echo 'Percentage Mode';
            } else if($drawMode['drawMode'] == 3) {
                echo 'Manual Mode';
            }?></b> <br />
            <?php if(($drawMode['drawMode'] == 1 || $drawMode['drawMode'] == 3) && $drawMode['isJackpot'] == 1) { ?>
                <b>Jackpot Mode : <?php if($drawMode['isJackpot'] == 1) {
                    echo 'On';
                } else {
                    echo 'Off';
                } ?></b>
                <br />
                <b>Jackpot Value : <?php echo $drawMode['jackpotValue'].'X'; ?></b>
                <br />
            <?php } ?>
            
            <?php if($drawMode['drawMode'] == 2) { ?>
                <b>Percentage : <?php echo $drawMode['percentage'].'%'; ?></b><br />
            <?php } ?>
            
            <?php if($drawMode['drawMode'] == 3) { ?>
                <b>Yantra : <?php echo $drawMode['manual']; ?></b><br />
            <?php } ?>
                
        </div>
        <div id="counter">
            <div id="counter_item1" class="counter_item">
                <div class="front"></div>
                <div class="digit digit0"></div>
            </div>
            <div id="counter_item2" class="counter_item">
                <div class="front"></div>
                <div class="digit digit0"></div>
            </div>
            <div id="counter_item3" class="counter_item">
                <div class="front"></div>
                <div class="digit digit_colon"></div>
            </div>
            <div id="counter_item4" class="counter_item">
                <div class="front"></div>
                <div class="digit digit0"></div>
            </div>
            <div id="counter_item5" class="counter_item">
                <div class="front"></div>
                <div class="digit digit0"></div>
            </div>
        </div>
        <div class="pull-right" style="margin-top:-87px;">
            <button onclick="window.location.reload();" class="btn btn-warning btn-lg pull-left" style="margin-top: 37px;margin-bottom: 18px;margin-right:21px;">
                Refresh
            </button>
            <button class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#showDrawList" style="margin-top: 37px;margin-bottom: 18px;">
                Show Draw Yantra
            </button>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>1</th>
                    <th>2</th>
                    <th>3</th>
                    <th>4</th>
                    <th>5</th>
                    <th>6</th>
                    <th>7</th>
                    <th>8</th>
                    <th>9</th>
                    <th>10</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Quantity</td>
                    <th><?php echo isset($rate[1])?$rate[1]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[2])?$rate[2]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[3])?$rate[3]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[4])?$rate[4]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[5])?$rate[5]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[6])?$rate[6]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[7])?$rate[7]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[8])?$rate[8]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[9])?$rate[9]['quantity']:0; ?></th>
                    <th><?php echo isset($rate[10])?$rate[10]['quantity']:0; ?></th>
                    <td><?php echo $totalRate['totalQnt']; ?></td>
                </tr>
                <tr>
                    <td>Price</td>
                    <th><?php echo isset($rate[1])?$rate[1]['price']:0; ?></th>
                    <th><?php echo isset($rate[2])?$rate[2]['price']:0; ?></th>
                    <th><?php echo isset($rate[3])?$rate[3]['price']:0; ?></th>
                    <th><?php echo isset($rate[4])?$rate[4]['price']:0; ?></th>
                    <th><?php echo isset($rate[5])?$rate[5]['price']:0; ?></th>
                    <th><?php echo isset($rate[6])?$rate[6]['price']:0; ?></th>
                    <th><?php echo isset($rate[7])?$rate[7]['price']:0; ?></th>
                    <th><?php echo isset($rate[8])?$rate[8]['price']:0; ?></th>
                    <th><?php echo isset($rate[9])?$rate[9]['price']:0; ?></th>
                    <th><?php echo isset($rate[10])?$rate[10]['price']:0; ?></th>
                    <td><?php echo $totalRate['totalPrice']; ?></td>
                </tr>
                <tr style="color: blue;">
                    <td>Win Price</td>
                    <th><?php echo isset($rate[1])?$rate[1]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[2])?$rate[2]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[3])?$rate[3]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[4])?$rate[4]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[5])?$rate[5]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[6])?$rate[6]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[7])?$rate[7]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[8])?$rate[8]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[9])?$rate[9]['winPrice']:0; ?></th>
                    <th><?php echo isset($rate[10])?$rate[10]['winPrice']:0; ?></th>
                    <td>-</td>
                </tr>
                <tr style="color: blue;">
                    <td>P/L</td>
                    <th><?php echo isset($rate[1])?$rate[1]['PL']:0; ?></th>
                    <th><?php echo isset($rate[2])?$rate[2]['PL']:0; ?></th>
                    <th><?php echo isset($rate[3])?$rate[3]['PL']:0; ?></th>
                    <th><?php echo isset($rate[4])?$rate[4]['PL']:0; ?></th>
                    <th><?php echo isset($rate[5])?$rate[5]['PL']:0; ?></th>
                    <th><?php echo isset($rate[6])?$rate[6]['PL']:0; ?></th>
                    <th><?php echo isset($rate[7])?$rate[7]['PL']:0; ?></th>
                    <th><?php echo isset($rate[8])?$rate[8]['PL']:0; ?></th>
                    <th><?php echo isset($rate[9])?$rate[9]['PL']:0; ?></th>
                    <th><?php echo isset($rate[10])?$rate[10]['PL']:0; ?></th>
                    <td>-</td>
                </tr>
                <tr style="color: red;">
                    <td>Jack Win Price</td>
                    <th><?php echo isset($rate[1])?$rate[1]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[2])?$rate[2]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[3])?$rate[3]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[4])?$rate[4]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[5])?$rate[5]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[6])?$rate[6]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[7])?$rate[7]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[8])?$rate[8]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[9])?$rate[9]['jackpotWinPrice']:0; ?></th>
                    <th><?php echo isset($rate[10])?$rate[10]['jackpotWinPrice']:0; ?></th>
                    <td>-</td>
                </tr>
                <tr style="color: red;">
                    <td>Jack P/L</td>
                    <th><?php echo isset($rate[1])?$rate[1]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[2])?$rate[2]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[3])?$rate[3]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[4])?$rate[4]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[5])?$rate[5]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[6])?$rate[6]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[7])?$rate[7]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[8])?$rate[8]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[9])?$rate[9]['jackpotPL']:0; ?></th>
                    <th><?php echo isset($rate[10])?$rate[10]['jackpotPL']:0; ?></th>
                    <td>-</td>
                </tr>                
            </tbody>
        </table>
    </div>
    <!-- /.row -->
    <div class="row text-center">
        <div class="panel panel-primary pull-left" style="width: 92%;margin-left: 30px;">
            <div class="panel-heading">
                Draw Mode Panel
            </div>
            <form role="form" id="drawModefrm" method="post" action="<?php echo $this->basePath() ?>/admin/saveDrowMode">
                <div class="panel-body">
                
                    <div class="form-group">
                        <label>Select Draw Mode</label>
                        <select class="form-control" name="drawMode" id="drawMode">
                            <option value="1">Minimum Mode</option>
                            <option value="2">Percentage Mode</option>                            
                            <option value="3">Manual Mode</option>
                        </select>
                    </div>
                    <div class="form-group checkbox">
                        <input id="jackpotMode" data-toggle="toggle" data-on="Jackpot ON" data-off="Jackpot OFF" data-onstyle="success" data-offstyle="danger" type="checkbox" name="jackpotToggle">
                    </div>
                    <input type="hidden" name="isJackpot" id="jackpotmodeVal" value="0">
                    <div class="form-group" id="jackpotValueContent" style="display: none;">
                        <label>Select X By</label>
                        <select class="form-control" name="jackpotValue">
                            <option value="2">2X</option>
                            <option value="3">3X</option>
                            <option value="4">4X</option>
                            <option value="5">5X</option>
                        </select>
                    </div>
                    <div class="form-group" id="manualContent" style="display: none;">
                        <label>Select Yantra</label>
                        <select class="form-control" name="manual">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                            <option value="6">6</option>
                            <option value="7">7</option>
                            <option value="8">8</option>
                            <option value="9">9</option>
                            <option value="10">10</option>
                        </select>
                    </div>
                    <div class="form-group" id="percentageContent" style="display: none;">
                        <label>Percentage</label>
                        <select class="form-control" name="percentage">
                            <option value="5">5%</option>
                            <option value="10">10%</option>
                            <option value="15">15%</option>
                            <option value="20">20%</option>
                            <option value="25">25%</option>
                            <option value="30">30%</option>
                            <option value="35">35%</option>
                            <option value="40">40%</option>
                            <option value="50">50%</option>
                        </select>
                    </div>
                </div>
                <div class="panel-footer">
                    <button type="submit" class="btn btn-outline btn-primary btn-lg btn-block">Save Draw Mode</button>
                </div>
            </form>
        </div>

        <!--<div class="panel panel-red pull-left" style="width: 40%;margin-left: 30px;">
            <div class="panel-heading">
                Jackpot Panel
            </div>
            <div class="panel-body">

                <form role="form" id="jackpotfrm">
                    <div class="form-group checkbox">
                        <input id="jackpotMode" data-toggle="toggle" data-on="Jackpot ON" data-off="Jackpot OFF" data-onstyle="success" data-offstyle="danger" type="checkbox" name="jackpot">
                    </div>
                    <div class="form-group" id="jackpotValueContent" style="display: none;">
                        <label>Select X By</label>
                        <select class="form-control" name="jackpotValue">
                            <option value="2">2X</option>
                            <option value="3">3X</option>
                            <option value="4">4X</option>
                            <option value="5">5X</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <button type="button" class="btn btn-outline btn-primary btn-lg btn-block">Save Jackpot</button>
            </div>
        </div>-->
        <!-- /.col-lg-4 -->

    </div>
</div>
<!-- /#page-wrapper -->
<div class="modal fade" id="showDrawList" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Drow Yantra List</h4>
            </div>
            <div class="modal-body">
                <div class="text-center" style="height:350px;margin-left:26px;overflow: scroll;">
                <?php if(count($drawYantra) > 0) {
                    foreach ($drawYantra as $yantra){
                        ?>
                        <div style="width: 100px;margin-left: 3px;" class="pull-left">
                            <div class="panel panel-<?php echo ($yantra['jackpot'] > 1)?'red':'green'; ?>">
                                <div class="panel-heading text-center">
                                    <div class="row">
                                        <img width="50" src="<?php echo $this->basePath() ?>/yantraImages/<?php echo $yantra['yantraId'];?>.png">
                                    </div>
                                </div>

                                <div>
                                    <h5>
                                        <?php $dateArray = explode(' ',$yantra['drawTime']); echo $dateArray[1];?><?php echo ($yantra['jackpot'] > 1)?' ('.$yantra['jackpot'].'X)':''; ?>
                                    </h5>
                                </div>
                            </div>
                        </div>
                        <?php
                    }
                } ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>