<?php
echo $this->headScript()
          ->appendFile($this->basePath() . '/js/myjs/dashboard.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1></h1>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <?php 
        $start =  1;
        $end = 10;
        for ($i = $start; $i<=$end; $i++) {
        ?>
        <div style="width: 200px;margin-left: 30px;" class="pull-left">
            <div class="panel panel-green">
                <div class="panel-heading text-center">
                    <div class="row">
                        <img src="<?php echo $this->basePath() ?>/yantraImages/<?php echo $i;?>.png">
                    </div>
                </div>
                
                <div class="panel-footer" style="font-size: 20px;">
                    <b>
                        <span>Purchase : 5000</span><br />
                        <span>Profit : 5000</span><br />
                        <span>Loss : 0</span>
                    </b>
                </div>
            </div>
        </div>
        <?php
        }
        ?>
    </div>
    <!-- /.row -->
    <div class="row text-center">
        <div class="panel panel-primary pull-left" style="width: 40%;margin-left: 30px;">
            <div class="panel-heading">
                Draw Mode Panel
            </div>
            <div class="panel-body">
                <form role="form" id="drawModefrm">
                    <div class="form-group">
                        <label>Select Draw Mode</label>
                        <select class="form-control" name="drawMode" id="drawMode">
                            <option value="1">Minimum Mode</option>
                            <option value="2">Percentage Mode</option>                            
                            <option value="3">Manual Mode</option>
                        </select>
                    </div>
                    <div class="form-group" id="manualContent" style="display: none;">
                        <label>Select Yantra</label>
                        <select class="form-control" name="manual">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                        </select>
                    </div>
                    <div class="form-group" id="percentageContent" style="display: none;">
                        <label>Percentage</label>
                        <input class="form-control" placeholder="Eg:10">
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <button type="button" class="btn btn-outline btn-primary btn-lg btn-block">Save Draw Mode</button>
            </div>
        </div>
        
        <div class="panel panel-red pull-left" style="width: 40%;margin-left: 30px;">
            <div class="panel-heading">
                Jackpot Panel
            </div>
            <div class="panel-body">
                
                <form role="form" id="jackpotfrm">
                    <div class="form-group checkbox">
                        <input id="jackpotMode" data-toggle="toggle" data-on="Jackpot ON" data-off="Jackpot OFF" data-onstyle="success" data-offstyle="danger" type="checkbox" name="jackpot">
                    </div>
                    <div class="form-group" id="jackpotValueContent" style="display: none;">
                        <label>Select X By</label>
                        <select class="form-control" name="jackpotValue">
                            <option value="2">2X</option>
                            <option value="3">3X</option>
                            <option value="4">4X</option>
                            <option value="5">5X</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <button type="button" class="btn btn-outline btn-primary btn-lg btn-block">Save Jackpot</button>
            </div>
        </div>
        <!-- /.col-lg-4 -->

    </div>
</div>
<!-- /#page-wrapper -->