<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/daywiseReport.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Local Users - Daywise Reports</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Daywise Reports</b>
                    <span class="pull-right">
                        <form name="daywise" method="post">
                            <b>Start Date : </b><input type="text" id="startDate" name="startDate">
                            <b>End Date : </b><input type="text" id="endDate" name="endDate">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </span>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="daywiseRepoTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Draw Date</th>
                                    <th>Opening Bal.</th>
                                    <th>Purchase</th>
                                    <th>Win Bal.</th>
                                    <th>Credit Bal.</th>
                                    <th>Debit Bal</th>
                                    <th>Close Bal.</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($daywiseReport) > 0) {
                                    foreach ($daywiseReport as $report) {
                                        ?>
                                        <tr>
                                            <td><?=$report['drawDate']?></td>
                                            <td><?=$report['openingBal']?></td>
                                            <td><?=$report['purchase']?></td>
                                            <td><?=$report['win']?></td>
                                            <td><?=$report['creditBal']?></td>
                                            <td><?=$report['debitBal']?></td>
                                            <td><?=$report['closeBal']?></td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div><!-- /#page-wrapper -->