<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1></h1>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <?php if (count($usersData) > 0) {
                                foreach ($usersData as $user){
                                    if ($user['userRoll'] == 'local') {
                                        $totalUsers = $user['totalUsers'];
                                        $totalBal = $user['localBal'];
                                    }
                                }
                            }?>
                            <div style="font-size: 23px;">Local Users : <?=$totalUsers?></div>
                            <div>Total Available Bal : <?=$totalBal?></div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->basePath()?>/admin/localUsers">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-4 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-users fa-5x"></i>
                        </div>
                        <?php if (count($usersData) > 0) {
                                foreach ($usersData as $user){
                                    if ($user['userRoll'] == 'agent') {
                                        $totalUsers = $user['totalUsers'];
                                        $totalBal = $user['agentBal'];
                                    }
                                }
                            }?>
                        <div class="col-xs-9 text-right">
                            <div style="font-size: 23px;">Agent Users : <?=$totalUsers?></div>
                            <div>Total Available Bal : <?=$totalBal?></div>
                        </div>
                    </div>
                </div>
                <a href="<?php echo $this->basePath()?>/admin/agentUsers">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-5" style="margin-left:32%;">
            <a style="margin-top: 37px;margin-bottom: 18px;" target="_blank" href="<?php echo $this->basePath()?>/admin/dashboard" class="btn btn-danger btn-lg pull-left">
                Dashboard
            </a>
            
            <a style="margin-top: 37px;margin-bottom: 18px;" target="_blank" href="<?php echo $this->basePath()?>/admin/showDrawYantra" class="btn btn-warning btn-lg pull-right">
                Show Draw Yantra
            </a>
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->