<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/userList.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header pull-left">Local Users</h1>
            <button style="margin-top: 37px;" data-target="#newLocalUser" data-toggle="modal" class="btn btn-primary btn-lg pull-right">
                Create New Local User
            </button>
        </div>
        
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Local users list
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="localUserTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 5%;">Id</th>
                                    <th>Name</th>
                                    <th>Phone No</th>
                                    <th>Available Bal.</th>
                                    <th>Win Bal.</th>
                                    <th style="width: 9%;">Status</th>
                                    <th style="width: 20%;">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($localUser) > 0) {
                                    foreach ($localUser as $user) {
                                        ?>
                                        <tr>
                                            <td><?=$user['Id']?></td>
                                            <td><?=$user['name']?></td>
                                            <td><?=$user['phoneNo']?></td>
                                            <td><?=$user['avaiPurchaseBal']?></td>
                                            <td><?=$user['totalWinBal']?></td>
                                            <td class="text-center">
                                                <?php if ($user['accountStatus'] == 'Active') { 
                                                    ?>
                                                        <button class="btn btn-success btn-circle" type="button" title="Active">
                                                            <i class="fa fa-check"></i>
                                                        </button>
                                                    <?php
                                                } else {?>
                                                        <button class="btn btn-danger btn-circle" type="button" title="Deactive">
                                                            <i class="fa fa-pause"></i>
                                                        </button>
                                                <?php } ?>
                                            </td>
                                            <td class="tool-tip">
                                                <button data-placement="top" data-toggle="modal" data-target="#chageUserCredit" title="Change Credit" class="btn btn-primary btn-circle" type="button">
                                                    <i class="fa fa-money" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-warning btn-circle" data-target="#changeUserPassword" data-toggle="modal" type="button" data-placement="top" title="Change Password">
                                                    <i class="fa fa-key" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-primary btn-circle" data-content="<a href='<?php echo $this->basePath() ?>/admin/purchaseReport/<?=$user['Id']?>'>Purchase Report</a><br/><a href='<?php echo $this->basePath() ?>/admin/daywiseReport/<?=$user['Id']?>'>Daywise Report</a><br/><a href='<?php echo $this->basePath() ?>/admin/showwiseReport/<?=$user['Id']?>'>Showwise Report</a>" data-placement="bottom" data-toggle="popover" data-container="body" type="button" title="Show Reports">
                                                    <i class="fa fa-database" style="font-size: 1.4em;"></i>
                                                </button>
                                                <button class="btn btn-danger btn-circle" type="button" data-placement="top" data-toggle="tooltip" data-original-title="Delete User">
                                                    <i class="fa fa-trash" style="font-size: 1.4em;"></i>
                                                </button>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div><!-- /#page-wrapper -->
    
    <!-- Modal -->
    <div class="modal fade" id="newLocalUser" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Create New Local User</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/createUser">
                        <input value="local" type="hidden" name="userRoll">
                        <div class="form-group">
                            <label>Name</label>
                            <input placeholder="Enter Name" name="name" class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <label>Phone No</label>
                            <input placeholder="Enter Phone No" name="phoneNo" class="form-control">
                        </div>
                        
                        <div class="form-group">
                            <label>Password</label>
                            <input placeholder="Enter Password" name="password" class="form-control">
                        </div>
                        
                        <button class="btn btn-default" type="submit">Create User</button>
                        <button class="btn btn-default" type="reset">Reset Button</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    
     <div class="modal fade" id="changeUserPassword" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Change Password</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/changeUserPassword">
                        <input value="local" type="hidden" name="userRoll">
                        <div class="form-group">
                            <label>New Password</label>
                            <input placeholder="Enter New Password" name="password" class="form-control">
                        </div>
                        
                        <button class="btn btn-default" type="submit">Update Password</button>
                        <button class="btn btn-default" type="reset">Reset Button</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
     </div>
    
     <div class="modal fade" id="chageUserCredit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Change User Credit</h4>
                </div>
                <div class="modal-body">
                    <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/changeUserCredit">
                        <input value="local" type="hidden" name="userRoll">
                        
                        <div class="form-group">
                            <label>Select Balance Action Type</label>
                            <select class="form-control">
                                <option>Credit</option>
                                <option>Debit</option>
                            </select>
                        </div>
                        
                        <div class="form-group">
                            <label>Balance</label>
                            <input placeholder="Enter Balance" name="password" class="form-control">
                        </div>
                        
                        <button class="btn btn-default" type="submit">Save</button>
                        <button class="btn btn-default" type="reset">Reset Button</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
     </div>