<?php
$this->layout('layout/empty');
?>
<!--------CONTACT DETAILS POPUP----------------->

<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Mobile Yantra - Admin Sign In</h3>
                </div>
                <?php
                    if ($loginError == true) {
                ?>
                    <div class="alert alert-danger alert-dismissable">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        Login Fail...
                    </div>
                <?php } ?>
                <div class="panel-body">
                    <form role="form" name="login-frm" method="post" action="/public/admin/login">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="User Name" name="uname" type="text" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                </label>
                            </div>
                            <!-- Change this to a button or input when using this as a form -->
                            <input type="submit" value="Login" class="btn btn-lg btn-success btn-block">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

