<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/purchaseReport.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Profit/Loss Reports</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Purchase Reports</b>
                    <span class="pull-right">
                        <form name="purchase" method="post">
                            <b>Select Date : </b><input type="text" id="date" name="date">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </span>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="purchaseRepoTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 20%;">Draw Time</th>
                                    <th style="width: 15%;">Draw Yantra</th>
                                    <th style="width: 8%;">Jackpot</th>
                                    <th style="width: 8%;">Purchase</th>
                                    <th style="width: 10%;">Win Price</th>
                                    <th style="width: 5%;">P/L</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($plReport) > 0) {
                                    foreach ($plReport as $report) {
                                        ?>
                                        <tr>
                                            <td><?php $date = explode(" ",$report['drawTime']); echo date('h:i a',strtotime($date[1]));?></td>
                                            <td><?=$report['yantraId']?></td>
                                            <td><?=$report['jackpot']?></td>
                                            <td><?=$report['purchase']?></td>
                                            <td><?=$report['winPrice']?></td>
                                            <td><?=$report['pl']?></td>
                                       </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div><!-- /#page-wrapper -->