<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/purchaseReport.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Local Users - Purchase Reports</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Purchase Reports</b>
                    <span class="pull-right">
                        <form name="purchase" method="post">
                            <b>Select Date : </b><input type="text" id="date" name="date">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </span>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="purchaseRepoTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 20%;">Draw Time</th>
                                    <th style="width: 5%;">1</th>
                                    <th style="width: 5%;">2</th>
                                    <th style="width: 5%;">3</th>
                                    <th style="width: 5%;">4</th>
                                    <th style="width: 5%;">5</th>
                                    <th style="width: 5%;">6</th>
                                    <th style="width: 5%;">7</th>
                                    <th style="width: 5%;">8</th>
                                    <th style="width: 5%;">9</th>
                                    <th style="width: 5%;">10</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($purchaseReport) > 0) {
                                    foreach ($purchaseReport as $report) {
                                        ?>
                                        <tr>
                                            <td><?=$report['time']?></td>
                                            <td><?=isset($report['1'])?$report['1']:0;?></td>
                                            <td><?=isset($report['2'])?$report['2']:0;?></td>
                                            <td><?=isset($report['3'])?$report['3']:0;?></td>
                                            <td><?=isset($report['4'])?$report['4']:0;?></td>
                                            <td><?=isset($report['5'])?$report['5']:0;?></td>
                                            <td><?=isset($report['6'])?$report['6']:0;?></td>
                                            <td><?=isset($report['7'])?$report['7']:0;?></td>
                                            <td><?=isset($report['8'])?$report['8']:0;?></td>
                                            <td><?=isset($report['9'])?$report['9']:0;?></td>
                                            <td><?=isset($report['10'])?$report['10']:0;?></td>
                                            <td><?=$report['total']?></td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div><!-- /#page-wrapper -->