<?php
$this->layout('layout/empty');
?>
<div class="row" style="margin-left: 50%;margin-top: 12px;">
    <a href="" class="btn btn-warning btn-lg pull-left">
        Refresh
    </a>
</div>
<div style="margin-top: 10px;">
    <?php if(count($drawYantra) > 0) {
        foreach ($drawYantra as $yantra){
            ?>
            <div style="width: 100px;margin-left: 3px;" class="pull-left">
                <div class="panel panel-<?php echo ($yantra['jackpot'] > 1)?'red':'green'; ?>">
                    <div class="panel-heading text-center">
                        <div class="row">
                            <img width="50" src="<?php echo $this->basePath() ?>/yantraImages/<?php echo $yantra['yantraId'];?>.png">
                        </div>
                    </div>

                    <div class="text-center">
                        <h5>
                            <?php $dateArray = explode(' ',$yantra['drawTime']); 
                                  echo date('h:i a',strtotime($dateArray[1]));
                            ?>
                            <?php echo ($yantra['jackpot'] > 1)?' ('.$yantra['jackpot'].'X)':''; ?>
                        </h5>
                    </div>
                </div>
            </div>
            <?php
        }
    } ?>
</div>


