<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/showwiseReport.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Local Users - Showwise Reports</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Showwise Reports</b>
                    <span class="pull-right">
                        <form name="showwise" method="post">
                            <b>Select Date : </b><input type="text" id="date" name="date">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </span>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="showwiseRepoTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Draw Date</th>
                                    <th>Show Time</th>
                                    <th>Purchase</th>
                                    <th>Win</th>
                                    <th>Symbol</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($showwiseReport) > 0) {
                                    foreach ($showwiseReport as $report) {
                                        ?>
                                        <tr>
                                            <td><?=$report['date']?></td>
                                            <td><?=$report['showTime']?></td>
                                            <td><?=$report['purchase']?></td>
                                            <td><?=$report['win']?></td>
                                            <td><?=$report['symbol']?></td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div><!-- /#page-wrapper -->