<?php
echo $this->headScript()
        ->appendFile($this->basePath() . '/js/myjs/tranferReport.js')
?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Agent User - Transfer Reports</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <b>Showwise Reports</b>
                    <span class="pull-right">
                        <form name="showwise" method="post">
                            <b>Select Date : </b><input type="text" id="date" name="date">
                            <button class="btn btn-success" type="submit">Search</button>
                        </form>
                    </span>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table id="transferRepoTbl" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Transfer To Name</th>
                                    <th>Transfer Type</th>
                                    <th>Transfer Balance</th>
                                    <th>Transfer Time</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (count($transferReport) > 0) {
                                    foreach ($transferReport as $report) {
                                        ?>
                                        <tr>
                                            <td><?=$report['name']?></td>
                                            <td><?=$report['transType']?></td>
                                            <td><?=$report['transBalance']?></td>
                                            <td><?=$report['time']?></td>
                                        </tr>
                                        <?php
                                    }
                                }
                                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div><!-- /#page-wrapper -->