<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        //set stylesheet
        echo $this->headLink()
                ->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.css')
                ->appendStylesheet($this->basePath() . '/css/bootstrap-toggle.min.css')
                ->appendStylesheet($this->basePath() . '/dist/css/sb-admin-2.css')
                ->appendStylesheet($this->basePath() . '/bower_components/fontawesome/css/font-awesome.min.css');

        // Set javascripts
        echo $this->headScript()
                ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
                ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.js')
                ->appendFile($this->basePath() . '/dist/js/sb-admin-2.js');
        ?>
    </head>
    <title>Mobile Yantra</title>
    <body>
        <div class="container">
            <?php $flashMessenger = $this->flashMessenger('error');      ?>
            <?php if ($flashMessenger->hasMessages()):   ?>
            <div class="alert alert-danger alert-dismissable pull-right" style="width: 77%;margin: 19px 3px 13px 0px;">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <?php foreach ($flashMessenger->getMessages() as $message):      ?>
            <?php echo $message  ?>  
            <?php endforeach   ?>
            </div>
            
            <?php endif; ?>
            <?php $flashMessenger->setNamespace('success');  ?>
            <?php if ($flashMessenger->hasMessages()):   ?>

            <div class="alert alert-success alert-dismissable pull-right" style="width: 77%;margin: 19px 3px 13px 0px;">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <?php foreach ($flashMessenger->getMessages() as $message):      ?>
            <?php echo $message  ?>		
            <?php endforeach;   ?>
            </div>
            <?php endif; ?>
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
