<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        //set stylesheet
        echo $this->headLink()->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.css')
                ->appendStylesheet($this->basePath() . '/dist/css/timeline.css')
                ->appendStylesheet($this->basePath() . '/dist/css/jquery-ui.css')
                ->appendStylesheet($this->basePath() . '/dist/css/sb-admin-2.css')
                ->appendStylesheet($this->basePath() . '/bower_components/morrisjs/morris.css')
                ->appendStylesheet($this->basePath() . '/bower_components/fontawesome/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/css/bootstrap-toggle.min.css')
                ->appendStylesheet($this->basePath() . '/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css')
                ->appendStylesheet($this->basePath() . '/bower_components/datatables-responsive/css/dataTables.responsive.css');

        // Set javascripts
        echo $this->headScript()
                ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
                ->appendFile($this->basePath() . '/dist/js/jquery-ui.js')
                ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.js')
                ->appendFile($this->basePath() . '/bower_components/raphael/raphael-min.js')
                ->appendFile($this->basePath() . '/bower_components/morrisjs/morris.min.js')
                ->appendFile($this->basePath() . '/dist/js/sb-admin-2.js')
                ->appendFile($this->basePath() . '/js/bootstrap-toggle.min.js')
                ->appendFile($this->basePath() . '/bower_components/DataTables/media/js/jquery.dataTables.min.js')
                ->appendFile($this->basePath() . '/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js');
        ?>

    </head>
    <title>Mobile Yantra</title>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <center><a class="navbar-brand" href="<?php echo $this->basePath() ?>/admin/home">Mobile Yantra Admin Panel</a></center>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-messages">
                            <li>
                                <a href="#">
                                    <div>
                                        <strong>Suresh</strong>
                                        <span class="pull-right text-muted">
                                            <em>Today</em>
                                        </span>
                                    </div>
                                    <div>New User Register 9974186581...</div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a class="text-center" href="#">
                                    <strong>Read All Messages</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </li>
                        </ul>
                        <!-- /.dropdown-messages -->
                    </li>
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="<?php echo $this->basePath() ?>/admin/home"><i class="fa fa-home fa-fw"></i> Home</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->basePath() ?>/admin/dashboard"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-users fa-fw"></i> Users<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/localUsers">Local Users</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/agentUsers">Agent Users</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-star fa-fw"></i> My Yantra</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-user fa-fw"></i> My Profile</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-files-o fa-fw"></i> My Reports</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>
             <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
