<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
        //set stylesheet
        echo $this->headLink()->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.css')
                ->appendStylesheet($this->basePath() . '/dist/css/timeline.css')
                ->appendStylesheet($this->basePath() . '/dist/css/jquery-ui.css')
                ->appendStylesheet($this->basePath() . '/dist/css/sb-admin-2.css')
                ->appendStylesheet($this->basePath() . '/bower_components/morrisjs/morris.css')
                ->appendStylesheet($this->basePath() . '/bower_components/fontawesome/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css')
                ->appendStylesheet($this->basePath() . '/bower_components/datatables-responsive/css/dataTables.responsive.css');

        // Set javascripts
        echo $this->headScript()
                ->appendFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
                ->appendFile($this->basePath() . '/dist/js/jquery-ui.js')
                ->appendFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/bower_components/metisMenu/dist/metisMenu.min.js')
                ->appendFile($this->basePath() . '/bower_components/raphael/raphael-min.js')
                ->appendFile($this->basePath() . '/bower_components/morrisjs/morris.min.js')
                ->appendFile($this->basePath() . '/dist/js/sb-admin-2.js')
                ->appendFile($this->basePath() . '/bower_components/datatables/media/js/jquery.dataTables.min.js')
                ->appendFile($this->basePath() . '/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js');
        ?>

    </head>
    <title>Mobile Yantra</title>
    <body>
        <div id="wrapper">
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <center><a class="navbar-brand" href="<?php echo $this->basePath() ?>/admin/home">Mobile Yantra Admin Panel</a></center>
                </div>
                <!-- /.navbar-header -->

                <ul class="nav navbar-top-links navbar-right">
                    <!-- /.dropdown -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user in">
                            <li>
                                <a href="#" class="active" data-toggle="modal" data-target="#changeAdminPassword"><i class="fa fa-key fa-fw"></i> Change Password</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="<?php echo $this->basePath() ?>/admin/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                <a href="<?php echo $this->basePath() ?>/admin/home"><i class="fa fa-home fa-fw"></i> Home</a>
                            </li>
                            <li>
                                <a href="<?php echo $this->basePath() ?>/admin/dashboard" target="_new"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-users fa-fw"></i> Users<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/localUsers">Local Users</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/agentUsers">Agent Users</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-newspaper-o fa-fw"></i> P/L Reports<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/plReports">Showwise Reports</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/daywisePlReports">Daywise Reports</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="javascript:void(0);"><i class="fa fa-newspaper-o fa-fw"></i> Transaction Reports<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/trReports">Transaction Reports</a>
                                    </li>
                                    <li>
                                        <a href="<?php echo $this->basePath() ?>/admin/daywiseTrReports">Daywise Transaction Reports</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a href="<?php echo $this->basePath() ?>/admin/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>                
            </nav>
            
            <?php $flashMessenger = $this->flashMessenger('error');      ?>
            <?php if ($flashMessenger->hasMessages()):   ?>
            <div class="alert alert-danger alert-dismissable pull-right" style="width: 77%;margin: 19px 3px 13px 0px;">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <?php foreach ($flashMessenger->getMessages() as $message):      ?>
            <?php echo $message  ?>  
            <?php endforeach   ?>
            </div>
            
            <?php endif; ?>
            <?php $flashMessenger->setNamespace('success');  ?>
            <?php if ($flashMessenger->hasMessages()):   ?>

            <div class="alert alert-success alert-dismissable pull-right" style="width: 77%;margin: 19px 3px 13px 0px;">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
            <?php foreach ($flashMessenger->getMessages() as $message):      ?>
            <?php echo $message  ?>		
            <?php endforeach;   ?>
            </div>
            <?php endif; ?>
            
            <?php echo $this->content; ?>
        </div>
        <div class="modal fade" id="changeAdminPassword" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Change Admin Password</h4>
                    </div>
                    <div class="modal-body">
                        <form role="form" method="post" action="<?php echo $this->basePath() ?>/admin/changeAdminPassword">
                            <div class="form-group">
                                <label>Old Password</label>
                                <input placeholder="Enter Old Password" name="oldPassword" class="form-control">
                            </div>
                            <div class="form-group">
                                <label>New Password</label>
                                <input placeholder="Enter New Password" name="newPassword" class="form-control">
                            </div>
                            <button class="btn btn-default" type="submit">Update Password</button>
                            <button class="btn btn-default" type="reset">Reset Button</button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
